- name: Make sure package metadata is up to date
  package:
    update_cache: true

- name: Install LDAP Server
  import_tasks: ldap-server.yaml
  tags: ldap

- name: define LDAP variables
  set_fact:
    ldap_zone_dn: "dc={{ ansible_domain.split('.') | join(',dc=') }}"
    ldap_host_dn: "cn={{ ansible_hostname }},dc={{ ansible_domain.split('.') | join(',dc=') }}"
    ldap_admin_dn: "cn={{ ldap.bind_cn }},dc={{ ansible_domain.split('.') | join(',dc=') }}"
  tags:
    - dhcp
    - dhcp_config
  
- name: Configure DHCP Server (LDAP)
  import_tasks: dhcp-config.yaml
  tags: dhcp_config
  
- name: Install DHCP Server
  import_tasks: dhcp-server.yaml
  tags: dhcp
